language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: aK9Dbo3nvaJCZUtqRqO3qblD0sn3jEHDmd3Dugy7R0h5v4Jlk6k6VyCEp/ohAppAe5cHBsvM/oSrLvD/bW/W+GhXE1tQC+FMINJ5/ZtoeaKeQYwCBsu9MEwep0HVqPI22mFzmvA47rAUZUtTFarYwa4aLej9csnf7BANS2XBSFOsnUQPEVuqz0PRV6m+5wgh0ZzC9ts/Ox3jvQFURoX2MbKiCO3yTNTcVwTWep3Rm+jg2NlUL9vIV+C3ysqfrFDP0GzPjZvVM929n2hS5av8F7X/PCKcEF2qKQY72lpXa2zUFcnOIcCW6j8ICXzketnfvhKi+yUlv+92o7zkSTiDXbrqMVqJUgYaOo3tjJgRrzKLyhbw44q8/KxSbv1GCKwXqh6/T+ZygCVCdJADeCYBhKAc5GGxBppv2f0lyTsbU3ZDnVsxZWyDciSwervi5gskDbfU4VnEFOuG7HJ6YXT/Tp18EMbdMcCeKvpJX/thXdChQa0JyQi38SjpxTUDcOIHzi/QaMUtg12/N7zYd9o++csv/u+IpSeep4Q06AhUtpLkPoPy4fzWNE6khAGbcknHw1Al1NE1AgYOBU0LCJUecLxHyw4KTXsClJ90Dxgax1T8GLFPZSwVnEZnHegAWp54Wp8sJnQ0iWnI/qRw+/XY/gEzSs7fkld11XokQsHtlzI=
  app: shielded-wave-66120
  skip_cleanup: true